config/routes.rb
Rails.application.routes.draw do
  resources :logs

  root :to => 'twis#index'

  get 'twis/index'
  get 'twis/index/:days' => 'twis#index'

end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/logs.rb
class Logs < ActiveRecord::Base
end

app/controllers/application_controller.rb
# coding: utf-8

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/logs_controller.rb
# coding: utf-8

class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]

  # GET /logs
  # GET /logs.json
  def index
    @logs = Logs.all
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
  end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      params.require(:log).permit(:count, :date)
    end
end

app/controllers/twis_controller.rb
# coding: utf-8

class TwisController < ApplicationController
  def index
    @log = Logs.all
    days = get_daycount(0, Logs.all.count)
    # if days == -1 # error function FIXME
    @chart_data = Logs.select(:date, :count).limit(days).order(date: :desc).pluck(:date, :count)
  end

  private
  def get_daycount(min, max)
    days = params[:days].to_i
    if days <= min or days > max
      7
    else
      days
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/twis_helper.rb
module TwisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>I don't wanna go there</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override", :cache => true %>
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">I don't wanna go there</a> <a href="https://twitter.com/1d0ntwanna5" target="_blank">@1d0ntwanna5</a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
		  <!--
		  <li><a href="#"><%= t("web-app-theme.profile", :default => "Profile") %></a></li>
          <li><a href="#"><%= t("web-app-theme.settings", :default => "Settings") %></a></li>
          <li><a href="/logout" class="logout"><%= t("web-app-theme.logout", :default => "Logout") %></a></li>
		  -->
		  <li>Are you a person who wants to stay home?</li>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf"></ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> <a href="http://ogatube.com/">Tsubasa Ogawa</a>.</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/logs/_form.html.erb
<%= form_for(@log) do |f| %>
  <% if @log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% @log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing log</h1>

<%= render 'form' %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<h1>Listing logs</h1>

<table>
  <thead>
    <tr>
      <th>Count</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.count %></td>
        <td><%= log.date %></td>
        <td><%= link_to 'Show', log %></td>
        <td><%= link_to 'Edit', edit_log_path(log) %></td>
        <td><%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Log', new_log_path %>

app/views/logs/new.html.erb
<h1>New log</h1>

<%= render 'form' %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Count:</strong>
  <%= @log.count %>
</p>

<p>
  <strong>Date:</strong>
  <%= @log.date %>
</p>

<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>

app/views/twis/add.html.erb
<h1>Twis#add</h1>
<%= form_for Log.new do |f| %>
  <%= f.label :date %>
  <%= f.text_field :date %>
  <%= f.label :count %>
  <%= f.text_field :count %>
  <%= f.submit %>
<% end %>

app/views/twis/index.html.erb
<p id="day_selector">
scope: last 
<a href="/twis/index/7">a week</a> / 
<a href="/twis/index/31">a month</a> / 
<a href="/twis/index/365">a year</a>
</p>
<p>
<%= line_chart @chart_data,
      :library => {
	    :vAxis => { :title => '# of annoy people' },
		:backgroundColor => { :stroke => '#000000', :strokeWidth => 1, :fill => '#f2f2e2' }
	  }
%>
</p>
<hr>
<h2>Recent Annoy People</h2>
<p>
<a class="twitter-timeline" href="https://twitter.com/search?q=%28%E5%AD%A6%E6%A0%A1+OR+%E4%BC%9A%E7%A4%BE+OR+%E4%BB%95%E4%BA%8B%29+AND+%28%E3%81%84%E3%81%8D%E3%81%9F%E3%81%8F%E3%81%AA%E3%81%84+OR+%E8%A1%8C%E3%81%8D%E3%81%9F%E3%81%8F%E3%81%AA%E3%81%84%29" data-widget-id="516614847912353792">Tweets</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</p>

app/views/twis/tweetget.html.erb
<h1>Twis#tweetget</h1>
<h2>tweet is obtained and written to the db successfully.</h2>
<p></p>